### ISSUE TITLE
NUTS coroutines don't work on Python 3.11

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1473]
```
 Traceback (most recent call last):
Testing notebooks
  File "/home/runner/work/pints/pints/run-tests.py", line 584, in <module>
Skipping ignored notebook: examples/interfaces/statsmodels-arima.ipynb
    run_notebook_tests()
  File "/home/runner/work/pints/pints/run-tests.py", line 376, in run_notebook_tests
    ok &= test_notebook(notebook)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pints/pints/run-tests.py", line 438, in test_notebook
    import pints
  File "/home/runner/work/pints/pints/pints/__init__.py", line 224, in <module>
    from ._mcmc._nuts import NoUTurnMCMC
  File "/home/runner/work/pints/pints/pints/_mcmc/_nuts.py", line 210, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

See notebooks: https://github.com/pints-team/pints/actions/runs/3407521360/jobs/5667241465

**Comment by MichaelClerx** [comment]
https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines

**Comment by MichaelClerx** [comment]
How about we rewrite and make NUTS work only on 3.8+?

Still a note in there for 3.3: https://github.com/pints-team/pints/blob/master/pints/_mcmc/_nuts.py#L506

@martinjrobins do you have time to look at this?

**Comment by DavAug** [comment]
I read up on this a little bit and it seems that we can simply remove the `asyncio.coroutine` decorator to make our NUTS implementation compatible with Python 3.11. The decorator is only needed to make generator-like coroutines compatible with the async/await functionality. But in our NUTS implementation we don't actually use Awaitables, so we should be able to simply remove the decorator.

**Comment by DavAug** [comment]
I agree, the implementation is quite complicated. 

What I was aiming at is that I don't think we need asyncio for our implementation. So simply removing the decorator should do the trick for us. 

This is because the yield and yield from statements work also without asyncio in Python. Asyncio just makes functions containing yield and yield from compatible with the async/await syntax. It may nevertheless be useful to rewrite the implementation of NUTS but for now I think we might be able to simply remove the decorators.
